/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 48
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 31
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  sym_variable = 2,
  anon_sym__PIPE_ = 3,
  anon_sym_u22a5 = 4,
  anon_sym_CARET_PIPE_CARET = 5,
  anon_sym_u22a4 = 6,
  anon_sym_TILDE = 7,
  anon_sym_u00ac = 8,
  anon_sym_LPAREN = 9,
  anon_sym_COMMA = 10,
  anon_sym_RPAREN = 11,
  anon_sym_forall = 12,
  anon_sym_SPACE = 13,
  anon_sym_u2200 = 14,
  anon_sym_exists = 15,
  anon_sym_u2203 = 16,
  anon_sym_DASH_GT = 17,
  anon_sym_u2192 = 18,
  anon_sym_AMP = 19,
  anon_sym_u2227 = 20,
  anon_sym_SLASH_BSLASH = 21,
  anon_sym_PIPE = 22,
  anon_sym_u2228 = 23,
  anon_sym_BSLASH_SLASH = 24,
  anon_sym_LT_DASH_GT = 25,
  anon_sym_u2194 = 26,
  anon_sym_EQ_EQ_EQ = 27,
  anon_sym_u2261 = 28,
  sym_plusrepr = 29,
  sym_multrepr = 30,
  sym_main = 31,
  sym_contradiction = 32,
  sym_tautology = 33,
  sym_notterm = 34,
  sym_predicate = 35,
  sym__forall_repr = 36,
  sym_forall_quantifier = 37,
  sym__exists_repr = 38,
  sym_exists_quantifier = 39,
  sym_quantifier = 40,
  sym_binder = 41,
  sym_impl_term = 42,
  sym_andrepr = 43,
  sym_orrepr = 44,
  sym_biconrepr = 45,
  sym_equivrepr = 46,
  sym__assoc_term_aux = 47,
  sym_assoc_term = 48,
  sym_paren_expr = 49,
  sym_expr = 50,
  aux_sym_predicate_repeat1 = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [sym_variable] = "variable",
  [anon_sym__PIPE_] = "_|_",
  [anon_sym_u22a5] = "\u22a5",
  [anon_sym_CARET_PIPE_CARET] = "^|^",
  [anon_sym_u22a4] = "\u22a4",
  [anon_sym_TILDE] = "~",
  [anon_sym_u00ac] = "\u00ac",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_forall] = "forall",
  [anon_sym_SPACE] = " ",
  [anon_sym_u2200] = "\u2200",
  [anon_sym_exists] = "exists",
  [anon_sym_u2203] = "\u2203",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_u2192] = "\u2192",
  [anon_sym_AMP] = "&",
  [anon_sym_u2227] = "\u2227",
  [anon_sym_SLASH_BSLASH] = "/\\",
  [anon_sym_PIPE] = "|",
  [anon_sym_u2228] = "\u2228",
  [anon_sym_BSLASH_SLASH] = "\\/",
  [anon_sym_LT_DASH_GT] = "<->",
  [anon_sym_u2194] = "\u2194",
  [anon_sym_EQ_EQ_EQ] = "===",
  [anon_sym_u2261] = "\u2261",
  [sym_plusrepr] = "plusrepr",
  [sym_multrepr] = "multrepr",
  [sym_main] = "main",
  [sym_contradiction] = "contradiction",
  [sym_tautology] = "tautology",
  [sym_notterm] = "notterm",
  [sym_predicate] = "predicate",
  [sym__forall_repr] = "_forall_repr",
  [sym_forall_quantifier] = "forall_quantifier",
  [sym__exists_repr] = "_exists_repr",
  [sym_exists_quantifier] = "exists_quantifier",
  [sym_quantifier] = "quantifier",
  [sym_binder] = "binder",
  [sym_impl_term] = "impl_term",
  [sym_andrepr] = "andrepr",
  [sym_orrepr] = "orrepr",
  [sym_biconrepr] = "biconrepr",
  [sym_equivrepr] = "equivrepr",
  [sym__assoc_term_aux] = "_assoc_term_aux",
  [sym_assoc_term] = "assoc_term",
  [sym_paren_expr] = "paren_expr",
  [sym_expr] = "expr",
  [aux_sym_predicate_repeat1] = "predicate_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [sym_variable] = sym_variable,
  [anon_sym__PIPE_] = anon_sym__PIPE_,
  [anon_sym_u22a5] = anon_sym_u22a5,
  [anon_sym_CARET_PIPE_CARET] = anon_sym_CARET_PIPE_CARET,
  [anon_sym_u22a4] = anon_sym_u22a4,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_u00ac] = anon_sym_u00ac,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_forall] = anon_sym_forall,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [anon_sym_u2200] = anon_sym_u2200,
  [anon_sym_exists] = anon_sym_exists,
  [anon_sym_u2203] = anon_sym_u2203,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_u2192] = anon_sym_u2192,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_u2227] = anon_sym_u2227,
  [anon_sym_SLASH_BSLASH] = anon_sym_SLASH_BSLASH,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_u2228] = anon_sym_u2228,
  [anon_sym_BSLASH_SLASH] = anon_sym_BSLASH_SLASH,
  [anon_sym_LT_DASH_GT] = anon_sym_LT_DASH_GT,
  [anon_sym_u2194] = anon_sym_u2194,
  [anon_sym_EQ_EQ_EQ] = anon_sym_EQ_EQ_EQ,
  [anon_sym_u2261] = anon_sym_u2261,
  [sym_plusrepr] = sym_plusrepr,
  [sym_multrepr] = sym_multrepr,
  [sym_main] = sym_main,
  [sym_contradiction] = sym_contradiction,
  [sym_tautology] = sym_tautology,
  [sym_notterm] = sym_notterm,
  [sym_predicate] = sym_predicate,
  [sym__forall_repr] = sym__forall_repr,
  [sym_forall_quantifier] = sym_forall_quantifier,
  [sym__exists_repr] = sym__exists_repr,
  [sym_exists_quantifier] = sym_exists_quantifier,
  [sym_quantifier] = sym_quantifier,
  [sym_binder] = sym_binder,
  [sym_impl_term] = sym_impl_term,
  [sym_andrepr] = sym_andrepr,
  [sym_orrepr] = sym_orrepr,
  [sym_biconrepr] = sym_biconrepr,
  [sym_equivrepr] = sym_equivrepr,
  [sym__assoc_term_aux] = sym__assoc_term_aux,
  [sym_assoc_term] = sym_assoc_term,
  [sym_paren_expr] = sym_paren_expr,
  [sym_expr] = sym_expr,
  [aux_sym_predicate_repeat1] = aux_sym_predicate_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [anon_sym__PIPE_] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u22a5] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET_PIPE_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u22a4] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00ac] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_forall] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u2200] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_exists] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u2203] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u2192] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u2227] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u2228] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u2194] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u2261] = {
    .visible = true,
    .named = false,
  },
  [sym_plusrepr] = {
    .visible = true,
    .named = true,
  },
  [sym_multrepr] = {
    .visible = true,
    .named = true,
  },
  [sym_main] = {
    .visible = true,
    .named = true,
  },
  [sym_contradiction] = {
    .visible = true,
    .named = true,
  },
  [sym_tautology] = {
    .visible = true,
    .named = true,
  },
  [sym_notterm] = {
    .visible = true,
    .named = true,
  },
  [sym_predicate] = {
    .visible = true,
    .named = true,
  },
  [sym__forall_repr] = {
    .visible = false,
    .named = true,
  },
  [sym_forall_quantifier] = {
    .visible = true,
    .named = true,
  },
  [sym__exists_repr] = {
    .visible = false,
    .named = true,
  },
  [sym_exists_quantifier] = {
    .visible = true,
    .named = true,
  },
  [sym_quantifier] = {
    .visible = true,
    .named = true,
  },
  [sym_binder] = {
    .visible = true,
    .named = true,
  },
  [sym_impl_term] = {
    .visible = true,
    .named = true,
  },
  [sym_andrepr] = {
    .visible = true,
    .named = true,
  },
  [sym_orrepr] = {
    .visible = true,
    .named = true,
  },
  [sym_biconrepr] = {
    .visible = true,
    .named = true,
  },
  [sym_equivrepr] = {
    .visible = true,
    .named = true,
  },
  [sym__assoc_term_aux] = {
    .visible = false,
    .named = true,
  },
  [sym_assoc_term] = {
    .visible = true,
    .named = true,
  },
  [sym_paren_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [aux_sym_predicate_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
};

static const TSSymbol ts_supertype_symbols[SUPERTYPE_COUNT] = {
  sym_expr,
};

static const TSMapSlice ts_supertype_map_slices[] = {
  [sym_expr] = {.index = 0, .length = 3},
};

static const TSSymbol ts_supertype_map_entries[] = {
  [0] =
    sym_assoc_term,
    sym_impl_term,
    sym_paren_expr,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '\n', 14,
        '&', 43,
        '(', 33,
        ')', 35,
        '*', 54,
        '+', 53,
        ',', 34,
        '-', 6,
        '/', 8,
        '<', 2,
        '=', 5,
        '\\', 3,
        '^', 11,
        '_', 25,
        'e', 24,
        'f', 19,
        '|', 46,
        '~', 31,
        0xac, 32,
        0x2192, 42,
        0x2194, 50,
        0x2200, 38,
        0x2203, 40,
        0x2227, 44,
        0x2228, 47,
        0x2261, 52,
        0x22a4, 30,
        0x22a5, 28,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 1:
      if (lookahead == '\t') SKIP(1);
      if (lookahead == ' ') ADVANCE(37);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(48);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(51);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(41);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(49);
      END_STATE();
    case 8:
      if (lookahead == '\\') ADVANCE(45);
      END_STATE();
    case 9:
      if (lookahead == '^') ADVANCE(29);
      END_STATE();
    case 10:
      if (lookahead == '_') ADVANCE(27);
      END_STATE();
    case 11:
      if (lookahead == '|') ADVANCE(9);
      END_STATE();
    case 12:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(12);
      if (('1' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'a') ADVANCE(18);
      if (('1' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'i') ADVANCE(21);
      if (('1' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'l') ADVANCE(36);
      if (('1' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'l') ADVANCE(17);
      if (('1' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'o') ADVANCE(20);
      if (('1' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'r') ADVANCE(15);
      if (('1' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 's') ADVANCE(23);
      if (('1' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 's') ADVANCE(39);
      if (('1' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 't') ADVANCE(22);
      if (('1' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'x') ADVANCE(16);
      if (('1' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '|') ADVANCE(10);
      if (('1' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_variable);
      if (('1' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym__PIPE_);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_u22a5);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_CARET_PIPE_CARET);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_u22a4);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_u00ac);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_forall);
      if (('1' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_u2200);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_exists);
      if (('1' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_u2203);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_u2192);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_u2227);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_SLASH_BSLASH);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_u2228);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_BSLASH_SLASH);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LT_DASH_GT);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_u2194);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_EQ_EQ_EQ);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_u2261);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_plusrepr);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_multrepr);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 12},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 12},
  [39] = {.lex_state = 12},
  [40] = {.lex_state = 12},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 12},
  [43] = {.lex_state = 12},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
    [anon_sym__PIPE_] = ACTIONS(1),
    [anon_sym_u22a5] = ACTIONS(1),
    [anon_sym_CARET_PIPE_CARET] = ACTIONS(1),
    [anon_sym_u22a4] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_u00ac] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_forall] = ACTIONS(1),
    [anon_sym_u2200] = ACTIONS(1),
    [anon_sym_exists] = ACTIONS(1),
    [anon_sym_u2203] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_u2192] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_u2227] = ACTIONS(1),
    [anon_sym_SLASH_BSLASH] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_u2228] = ACTIONS(1),
    [anon_sym_BSLASH_SLASH] = ACTIONS(1),
    [anon_sym_LT_DASH_GT] = ACTIONS(1),
    [anon_sym_u2194] = ACTIONS(1),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(1),
    [anon_sym_u2261] = ACTIONS(1),
    [sym_plusrepr] = ACTIONS(1),
    [sym_multrepr] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_main] = STATE(41),
    [sym_contradiction] = STATE(14),
    [sym_tautology] = STATE(14),
    [sym_notterm] = STATE(14),
    [sym_predicate] = STATE(14),
    [sym__forall_repr] = STATE(45),
    [sym_forall_quantifier] = STATE(36),
    [sym__exists_repr] = STATE(34),
    [sym_exists_quantifier] = STATE(36),
    [sym_quantifier] = STATE(42),
    [sym_binder] = STATE(14),
    [sym_impl_term] = STATE(31),
    [sym__assoc_term_aux] = STATE(30),
    [sym_assoc_term] = STATE(31),
    [sym_paren_expr] = STATE(11),
    [sym_expr] = STATE(47),
    [sym_variable] = ACTIONS(3),
    [anon_sym__PIPE_] = ACTIONS(5),
    [anon_sym_u22a5] = ACTIONS(5),
    [anon_sym_CARET_PIPE_CARET] = ACTIONS(7),
    [anon_sym_u22a4] = ACTIONS(7),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_u00ac] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_forall] = ACTIONS(13),
    [anon_sym_u2200] = ACTIONS(15),
    [anon_sym_exists] = ACTIONS(17),
    [anon_sym_u2203] = ACTIONS(19),
  },
  [STATE(2)] = {
    [sym_contradiction] = STATE(14),
    [sym_tautology] = STATE(14),
    [sym_notterm] = STATE(14),
    [sym_predicate] = STATE(14),
    [sym__forall_repr] = STATE(45),
    [sym_forall_quantifier] = STATE(36),
    [sym__exists_repr] = STATE(34),
    [sym_exists_quantifier] = STATE(36),
    [sym_quantifier] = STATE(42),
    [sym_binder] = STATE(14),
    [sym_impl_term] = STATE(31),
    [sym__assoc_term_aux] = STATE(30),
    [sym_assoc_term] = STATE(31),
    [sym_paren_expr] = STATE(11),
    [sym_expr] = STATE(32),
    [aux_sym_predicate_repeat1] = STATE(3),
    [sym_variable] = ACTIONS(3),
    [anon_sym__PIPE_] = ACTIONS(5),
    [anon_sym_u22a5] = ACTIONS(5),
    [anon_sym_CARET_PIPE_CARET] = ACTIONS(7),
    [anon_sym_u22a4] = ACTIONS(7),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_u00ac] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_forall] = ACTIONS(13),
    [anon_sym_u2200] = ACTIONS(15),
    [anon_sym_exists] = ACTIONS(17),
    [anon_sym_u2203] = ACTIONS(19),
  },
  [STATE(3)] = {
    [sym_contradiction] = STATE(14),
    [sym_tautology] = STATE(14),
    [sym_notterm] = STATE(14),
    [sym_predicate] = STATE(14),
    [sym__forall_repr] = STATE(45),
    [sym_forall_quantifier] = STATE(36),
    [sym__exists_repr] = STATE(34),
    [sym_exists_quantifier] = STATE(36),
    [sym_quantifier] = STATE(42),
    [sym_binder] = STATE(14),
    [sym_impl_term] = STATE(31),
    [sym__assoc_term_aux] = STATE(30),
    [sym_assoc_term] = STATE(31),
    [sym_paren_expr] = STATE(11),
    [sym_expr] = STATE(33),
    [aux_sym_predicate_repeat1] = STATE(4),
    [sym_variable] = ACTIONS(3),
    [anon_sym__PIPE_] = ACTIONS(5),
    [anon_sym_u22a5] = ACTIONS(5),
    [anon_sym_CARET_PIPE_CARET] = ACTIONS(7),
    [anon_sym_u22a4] = ACTIONS(7),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_u00ac] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_forall] = ACTIONS(13),
    [anon_sym_u2200] = ACTIONS(15),
    [anon_sym_exists] = ACTIONS(17),
    [anon_sym_u2203] = ACTIONS(19),
  },
  [STATE(4)] = {
    [sym_contradiction] = STATE(14),
    [sym_tautology] = STATE(14),
    [sym_notterm] = STATE(14),
    [sym_predicate] = STATE(14),
    [sym__forall_repr] = STATE(45),
    [sym_forall_quantifier] = STATE(36),
    [sym__exists_repr] = STATE(34),
    [sym_exists_quantifier] = STATE(36),
    [sym_quantifier] = STATE(42),
    [sym_binder] = STATE(14),
    [sym_impl_term] = STATE(31),
    [sym__assoc_term_aux] = STATE(30),
    [sym_assoc_term] = STATE(31),
    [sym_paren_expr] = STATE(11),
    [sym_expr] = STATE(46),
    [aux_sym_predicate_repeat1] = STATE(4),
    [sym_variable] = ACTIONS(21),
    [anon_sym__PIPE_] = ACTIONS(24),
    [anon_sym_u22a5] = ACTIONS(24),
    [anon_sym_CARET_PIPE_CARET] = ACTIONS(27),
    [anon_sym_u22a4] = ACTIONS(27),
    [anon_sym_TILDE] = ACTIONS(30),
    [anon_sym_u00ac] = ACTIONS(30),
    [anon_sym_LPAREN] = ACTIONS(33),
    [anon_sym_forall] = ACTIONS(36),
    [anon_sym_u2200] = ACTIONS(39),
    [anon_sym_exists] = ACTIONS(42),
    [anon_sym_u2203] = ACTIONS(45),
  },
  [STATE(5)] = {
    [sym_contradiction] = STATE(14),
    [sym_tautology] = STATE(14),
    [sym_notterm] = STATE(14),
    [sym_predicate] = STATE(14),
    [sym__forall_repr] = STATE(45),
    [sym_forall_quantifier] = STATE(36),
    [sym__exists_repr] = STATE(34),
    [sym_exists_quantifier] = STATE(36),
    [sym_quantifier] = STATE(42),
    [sym_binder] = STATE(14),
    [sym_impl_term] = STATE(31),
    [sym__assoc_term_aux] = STATE(30),
    [sym_assoc_term] = STATE(31),
    [sym_paren_expr] = STATE(11),
    [sym_expr] = STATE(37),
    [sym_variable] = ACTIONS(3),
    [anon_sym__PIPE_] = ACTIONS(5),
    [anon_sym_u22a5] = ACTIONS(5),
    [anon_sym_CARET_PIPE_CARET] = ACTIONS(7),
    [anon_sym_u22a4] = ACTIONS(7),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_u00ac] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_forall] = ACTIONS(13),
    [anon_sym_u2200] = ACTIONS(15),
    [anon_sym_exists] = ACTIONS(17),
    [anon_sym_u2203] = ACTIONS(19),
  },
  [STATE(6)] = {
    [sym_contradiction] = STATE(14),
    [sym_tautology] = STATE(14),
    [sym_notterm] = STATE(14),
    [sym_predicate] = STATE(14),
    [sym__forall_repr] = STATE(45),
    [sym_forall_quantifier] = STATE(36),
    [sym__exists_repr] = STATE(34),
    [sym_exists_quantifier] = STATE(36),
    [sym_quantifier] = STATE(42),
    [sym_binder] = STATE(14),
    [sym_impl_term] = STATE(31),
    [sym__assoc_term_aux] = STATE(30),
    [sym_assoc_term] = STATE(31),
    [sym_paren_expr] = STATE(11),
    [sym_expr] = STATE(44),
    [sym_variable] = ACTIONS(3),
    [anon_sym__PIPE_] = ACTIONS(5),
    [anon_sym_u22a5] = ACTIONS(5),
    [anon_sym_CARET_PIPE_CARET] = ACTIONS(7),
    [anon_sym_u22a4] = ACTIONS(7),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_u00ac] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_forall] = ACTIONS(13),
    [anon_sym_u2200] = ACTIONS(15),
    [anon_sym_exists] = ACTIONS(17),
    [anon_sym_u2203] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 16,
    ACTIONS(3), 1,
      sym_variable,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_forall,
    ACTIONS(15), 1,
      anon_sym_u2200,
    ACTIONS(17), 1,
      anon_sym_exists,
    ACTIONS(19), 1,
      anon_sym_u2203,
    STATE(12), 1,
      sym_paren_expr,
    STATE(29), 1,
      sym__assoc_term_aux,
    STATE(34), 1,
      sym__exists_repr,
    STATE(42), 1,
      sym_quantifier,
    STATE(45), 1,
      sym__forall_repr,
    ACTIONS(5), 2,
      anon_sym__PIPE_,
      anon_sym_u22a5,
    ACTIONS(7), 2,
      anon_sym_CARET_PIPE_CARET,
      anon_sym_u22a4,
    ACTIONS(9), 2,
      anon_sym_TILDE,
      anon_sym_u00ac,
    STATE(36), 2,
      sym_forall_quantifier,
      sym_exists_quantifier,
    STATE(14), 5,
      sym_contradiction,
      sym_tautology,
      sym_notterm,
      sym_predicate,
      sym_binder,
  [57] = 15,
    ACTIONS(3), 1,
      sym_variable,
    ACTIONS(13), 1,
      anon_sym_forall,
    ACTIONS(15), 1,
      anon_sym_u2200,
    ACTIONS(17), 1,
      anon_sym_exists,
    ACTIONS(19), 1,
      anon_sym_u2203,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    STATE(20), 1,
      sym_paren_expr,
    STATE(34), 1,
      sym__exists_repr,
    STATE(42), 1,
      sym_quantifier,
    STATE(45), 1,
      sym__forall_repr,
    ACTIONS(5), 2,
      anon_sym__PIPE_,
      anon_sym_u22a5,
    ACTIONS(7), 2,
      anon_sym_CARET_PIPE_CARET,
      anon_sym_u22a4,
    ACTIONS(9), 2,
      anon_sym_TILDE,
      anon_sym_u00ac,
    STATE(36), 2,
      sym_forall_quantifier,
      sym_exists_quantifier,
    STATE(14), 5,
      sym_contradiction,
      sym_tautology,
      sym_notterm,
      sym_predicate,
      sym_binder,
  [111] = 15,
    ACTIONS(3), 1,
      sym_variable,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_forall,
    ACTIONS(15), 1,
      anon_sym_u2200,
    ACTIONS(17), 1,
      anon_sym_exists,
    ACTIONS(19), 1,
      anon_sym_u2203,
    STATE(28), 1,
      sym_paren_expr,
    STATE(34), 1,
      sym__exists_repr,
    STATE(42), 1,
      sym_quantifier,
    STATE(45), 1,
      sym__forall_repr,
    ACTIONS(5), 2,
      anon_sym__PIPE_,
      anon_sym_u22a5,
    ACTIONS(7), 2,
      anon_sym_CARET_PIPE_CARET,
      anon_sym_u22a4,
    ACTIONS(9), 2,
      anon_sym_TILDE,
      anon_sym_u00ac,
    STATE(36), 2,
      sym_forall_quantifier,
      sym_exists_quantifier,
    STATE(14), 5,
      sym_contradiction,
      sym_tautology,
      sym_notterm,
      sym_predicate,
      sym_binder,
  [165] = 15,
    ACTIONS(3), 1,
      sym_variable,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_forall,
    ACTIONS(15), 1,
      anon_sym_u2200,
    ACTIONS(17), 1,
      anon_sym_exists,
    ACTIONS(19), 1,
      anon_sym_u2203,
    STATE(15), 1,
      sym_paren_expr,
    STATE(34), 1,
      sym__exists_repr,
    STATE(42), 1,
      sym_quantifier,
    STATE(45), 1,
      sym__forall_repr,
    ACTIONS(5), 2,
      anon_sym__PIPE_,
      anon_sym_u22a5,
    ACTIONS(7), 2,
      anon_sym_CARET_PIPE_CARET,
      anon_sym_u22a4,
    ACTIONS(9), 2,
      anon_sym_TILDE,
      anon_sym_u00ac,
    STATE(36), 2,
      sym_forall_quantifier,
      sym_exists_quantifier,
    STATE(14), 5,
      sym_contradiction,
      sym_tautology,
      sym_notterm,
      sym_predicate,
      sym_binder,
  [219] = 8,
    ACTIONS(52), 2,
      anon_sym_DASH_GT,
      anon_sym_u2192,
    ACTIONS(58), 2,
      anon_sym_LT_DASH_GT,
      anon_sym_u2194,
    ACTIONS(60), 2,
      anon_sym_EQ_EQ_EQ,
      anon_sym_u2261,
    ACTIONS(62), 2,
      sym_plusrepr,
      sym_multrepr,
    ACTIONS(50), 3,
      anon_sym_LF,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(54), 3,
      anon_sym_AMP,
      anon_sym_u2227,
      anon_sym_SLASH_BSLASH,
    ACTIONS(56), 3,
      anon_sym_PIPE,
      anon_sym_u2228,
      anon_sym_BSLASH_SLASH,
    STATE(7), 4,
      sym_andrepr,
      sym_orrepr,
      sym_biconrepr,
      sym_equivrepr,
  [257] = 7,
    ACTIONS(58), 2,
      anon_sym_LT_DASH_GT,
      anon_sym_u2194,
    ACTIONS(60), 2,
      anon_sym_EQ_EQ_EQ,
      anon_sym_u2261,
    ACTIONS(62), 2,
      sym_plusrepr,
      sym_multrepr,
    ACTIONS(54), 3,
      anon_sym_AMP,
      anon_sym_u2227,
      anon_sym_SLASH_BSLASH,
    ACTIONS(56), 3,
      anon_sym_PIPE,
      anon_sym_u2228,
      anon_sym_BSLASH_SLASH,
    ACTIONS(64), 3,
      anon_sym_LF,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    STATE(7), 4,
      sym_andrepr,
      sym_orrepr,
      sym_biconrepr,
      sym_equivrepr,
  [291] = 2,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 17,
      anon_sym_LF,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_u2192,
      anon_sym_AMP,
      anon_sym_u2227,
      anon_sym_SLASH_BSLASH,
      anon_sym_PIPE,
      anon_sym_u2228,
      anon_sym_BSLASH_SLASH,
      anon_sym_LT_DASH_GT,
      anon_sym_u2194,
      anon_sym_EQ_EQ_EQ,
      anon_sym_u2261,
      sym_plusrepr,
      sym_multrepr,
  [314] = 1,
    ACTIONS(70), 17,
      anon_sym_LF,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_u2192,
      anon_sym_AMP,
      anon_sym_u2227,
      anon_sym_SLASH_BSLASH,
      anon_sym_PIPE,
      anon_sym_u2228,
      anon_sym_BSLASH_SLASH,
      anon_sym_LT_DASH_GT,
      anon_sym_u2194,
      anon_sym_EQ_EQ_EQ,
      anon_sym_u2261,
      sym_plusrepr,
      sym_multrepr,
  [334] = 1,
    ACTIONS(72), 17,
      anon_sym_LF,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_u2192,
      anon_sym_AMP,
      anon_sym_u2227,
      anon_sym_SLASH_BSLASH,
      anon_sym_PIPE,
      anon_sym_u2228,
      anon_sym_BSLASH_SLASH,
      anon_sym_LT_DASH_GT,
      anon_sym_u2194,
      anon_sym_EQ_EQ_EQ,
      anon_sym_u2261,
      sym_plusrepr,
      sym_multrepr,
  [354] = 1,
    ACTIONS(74), 17,
      anon_sym_LF,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_u2192,
      anon_sym_AMP,
      anon_sym_u2227,
      anon_sym_SLASH_BSLASH,
      anon_sym_PIPE,
      anon_sym_u2228,
      anon_sym_BSLASH_SLASH,
      anon_sym_LT_DASH_GT,
      anon_sym_u2194,
      anon_sym_EQ_EQ_EQ,
      anon_sym_u2261,
      sym_plusrepr,
      sym_multrepr,
  [374] = 1,
    ACTIONS(76), 17,
      anon_sym_LF,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_u2192,
      anon_sym_AMP,
      anon_sym_u2227,
      anon_sym_SLASH_BSLASH,
      anon_sym_PIPE,
      anon_sym_u2228,
      anon_sym_BSLASH_SLASH,
      anon_sym_LT_DASH_GT,
      anon_sym_u2194,
      anon_sym_EQ_EQ_EQ,
      anon_sym_u2261,
      sym_plusrepr,
      sym_multrepr,
  [394] = 1,
    ACTIONS(78), 17,
      anon_sym_LF,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_u2192,
      anon_sym_AMP,
      anon_sym_u2227,
      anon_sym_SLASH_BSLASH,
      anon_sym_PIPE,
      anon_sym_u2228,
      anon_sym_BSLASH_SLASH,
      anon_sym_LT_DASH_GT,
      anon_sym_u2194,
      anon_sym_EQ_EQ_EQ,
      anon_sym_u2261,
      sym_plusrepr,
      sym_multrepr,
  [414] = 1,
    ACTIONS(80), 17,
      anon_sym_LF,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_u2192,
      anon_sym_AMP,
      anon_sym_u2227,
      anon_sym_SLASH_BSLASH,
      anon_sym_PIPE,
      anon_sym_u2228,
      anon_sym_BSLASH_SLASH,
      anon_sym_LT_DASH_GT,
      anon_sym_u2194,
      anon_sym_EQ_EQ_EQ,
      anon_sym_u2261,
      sym_plusrepr,
      sym_multrepr,
  [434] = 1,
    ACTIONS(82), 17,
      anon_sym_LF,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_u2192,
      anon_sym_AMP,
      anon_sym_u2227,
      anon_sym_SLASH_BSLASH,
      anon_sym_PIPE,
      anon_sym_u2228,
      anon_sym_BSLASH_SLASH,
      anon_sym_LT_DASH_GT,
      anon_sym_u2194,
      anon_sym_EQ_EQ_EQ,
      anon_sym_u2261,
      sym_plusrepr,
      sym_multrepr,
  [454] = 1,
    ACTIONS(84), 17,
      anon_sym_LF,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_u2192,
      anon_sym_AMP,
      anon_sym_u2227,
      anon_sym_SLASH_BSLASH,
      anon_sym_PIPE,
      anon_sym_u2228,
      anon_sym_BSLASH_SLASH,
      anon_sym_LT_DASH_GT,
      anon_sym_u2194,
      anon_sym_EQ_EQ_EQ,
      anon_sym_u2261,
      sym_plusrepr,
      sym_multrepr,
  [474] = 1,
    ACTIONS(86), 17,
      anon_sym_LF,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_u2192,
      anon_sym_AMP,
      anon_sym_u2227,
      anon_sym_SLASH_BSLASH,
      anon_sym_PIPE,
      anon_sym_u2228,
      anon_sym_BSLASH_SLASH,
      anon_sym_LT_DASH_GT,
      anon_sym_u2194,
      anon_sym_EQ_EQ_EQ,
      anon_sym_u2261,
      sym_plusrepr,
      sym_multrepr,
  [494] = 2,
    ACTIONS(88), 3,
      sym_variable,
      anon_sym_forall,
      anon_sym_exists,
    ACTIONS(90), 9,
      anon_sym__PIPE_,
      anon_sym_u22a5,
      anon_sym_CARET_PIPE_CARET,
      anon_sym_u22a4,
      anon_sym_TILDE,
      anon_sym_u00ac,
      anon_sym_LPAREN,
      anon_sym_u2200,
      anon_sym_u2203,
  [511] = 2,
    ACTIONS(92), 3,
      sym_variable,
      anon_sym_forall,
      anon_sym_exists,
    ACTIONS(94), 9,
      anon_sym__PIPE_,
      anon_sym_u22a5,
      anon_sym_CARET_PIPE_CARET,
      anon_sym_u22a4,
      anon_sym_TILDE,
      anon_sym_u00ac,
      anon_sym_LPAREN,
      anon_sym_u2200,
      anon_sym_u2203,
  [528] = 2,
    ACTIONS(96), 3,
      sym_variable,
      anon_sym_forall,
      anon_sym_exists,
    ACTIONS(98), 9,
      anon_sym__PIPE_,
      anon_sym_u22a5,
      anon_sym_CARET_PIPE_CARET,
      anon_sym_u22a4,
      anon_sym_TILDE,
      anon_sym_u00ac,
      anon_sym_LPAREN,
      anon_sym_u2200,
      anon_sym_u2203,
  [545] = 2,
    ACTIONS(100), 3,
      sym_variable,
      anon_sym_forall,
      anon_sym_exists,
    ACTIONS(102), 9,
      anon_sym__PIPE_,
      anon_sym_u22a5,
      anon_sym_CARET_PIPE_CARET,
      anon_sym_u22a4,
      anon_sym_TILDE,
      anon_sym_u00ac,
      anon_sym_LPAREN,
      anon_sym_u2200,
      anon_sym_u2203,
  [562] = 2,
    ACTIONS(104), 3,
      sym_variable,
      anon_sym_forall,
      anon_sym_exists,
    ACTIONS(106), 9,
      anon_sym__PIPE_,
      anon_sym_u22a5,
      anon_sym_CARET_PIPE_CARET,
      anon_sym_u22a4,
      anon_sym_TILDE,
      anon_sym_u00ac,
      anon_sym_LPAREN,
      anon_sym_u2200,
      anon_sym_u2203,
  [579] = 1,
    ACTIONS(108), 3,
      anon_sym_LF,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [585] = 1,
    ACTIONS(110), 3,
      anon_sym_LF,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [591] = 1,
    ACTIONS(112), 3,
      anon_sym_LF,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [597] = 1,
    ACTIONS(50), 3,
      anon_sym_LF,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [603] = 2,
    ACTIONS(114), 1,
      anon_sym_COMMA,
    ACTIONS(116), 1,
      anon_sym_RPAREN,
  [610] = 2,
    ACTIONS(114), 1,
      anon_sym_COMMA,
    ACTIONS(118), 1,
      anon_sym_RPAREN,
  [617] = 1,
    ACTIONS(120), 1,
      anon_sym_SPACE,
  [621] = 1,
    ACTIONS(122), 1,
      ts_builtin_sym_end,
  [625] = 1,
    ACTIONS(124), 1,
      sym_variable,
  [629] = 1,
    ACTIONS(126), 1,
      anon_sym_RPAREN,
  [633] = 1,
    ACTIONS(128), 1,
      sym_variable,
  [637] = 1,
    ACTIONS(130), 1,
      sym_variable,
  [641] = 1,
    ACTIONS(132), 1,
      sym_variable,
  [645] = 1,
    ACTIONS(134), 1,
      ts_builtin_sym_end,
  [649] = 1,
    ACTIONS(136), 1,
      sym_variable,
  [653] = 1,
    ACTIONS(138), 1,
      sym_variable,
  [657] = 1,
    ACTIONS(140), 1,
      anon_sym_RPAREN,
  [661] = 1,
    ACTIONS(142), 1,
      anon_sym_SPACE,
  [665] = 1,
    ACTIONS(114), 1,
      anon_sym_COMMA,
  [669] = 1,
    ACTIONS(144), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 57,
  [SMALL_STATE(9)] = 111,
  [SMALL_STATE(10)] = 165,
  [SMALL_STATE(11)] = 219,
  [SMALL_STATE(12)] = 257,
  [SMALL_STATE(13)] = 291,
  [SMALL_STATE(14)] = 314,
  [SMALL_STATE(15)] = 334,
  [SMALL_STATE(16)] = 354,
  [SMALL_STATE(17)] = 374,
  [SMALL_STATE(18)] = 394,
  [SMALL_STATE(19)] = 414,
  [SMALL_STATE(20)] = 434,
  [SMALL_STATE(21)] = 454,
  [SMALL_STATE(22)] = 474,
  [SMALL_STATE(23)] = 494,
  [SMALL_STATE(24)] = 511,
  [SMALL_STATE(25)] = 528,
  [SMALL_STATE(26)] = 545,
  [SMALL_STATE(27)] = 562,
  [SMALL_STATE(28)] = 579,
  [SMALL_STATE(29)] = 585,
  [SMALL_STATE(30)] = 591,
  [SMALL_STATE(31)] = 597,
  [SMALL_STATE(32)] = 603,
  [SMALL_STATE(33)] = 610,
  [SMALL_STATE(34)] = 617,
  [SMALL_STATE(35)] = 621,
  [SMALL_STATE(36)] = 625,
  [SMALL_STATE(37)] = 629,
  [SMALL_STATE(38)] = 633,
  [SMALL_STATE(39)] = 637,
  [SMALL_STATE(40)] = 641,
  [SMALL_STATE(41)] = 645,
  [SMALL_STATE(42)] = 649,
  [SMALL_STATE(43)] = 653,
  [SMALL_STATE(44)] = 657,
  [SMALL_STATE(45)] = 661,
  [SMALL_STATE(46)] = 665,
  [SMALL_STATE(47)] = 669,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_predicate_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_predicate_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_predicate_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_predicate_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_predicate_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_predicate_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_predicate_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_predicate_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_predicate_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__assoc_term_aux, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren_expr, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_notterm, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tautology, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_contradiction, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate, 5, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren_expr, 3, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binder, 3, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate, 4, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binder, 5, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_andrepr, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_andrepr, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_orrepr, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_orrepr, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_biconrepr, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_biconrepr, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_predicate_repeat1, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_predicate_repeat1, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_equivrepr, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_equivrepr, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_impl_term, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__assoc_term_aux, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assoc_term, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_main, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quantifier, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_forall_quantifier, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_forall_quantifier, 1, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exists_quantifier, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exists_quantifier, 1, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_bram(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .supertype_map_slices = ts_supertype_map_slices,
    .supertype_map_entries = ts_supertype_map_entries,
    .supertype_symbols = ts_supertype_symbols,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "bram",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
